### ISSUE TITLE
Warning:Tailwind is not purging unused styles because no template paths have been provided

### ISSUE THREAD

**Issue by nagad814** [tailwindclub/tailwindv2-parcel#1]
I think the purgeCSS is not working as expected. my bundle size is 6MB

**Comment by aikodes** [comment]
I think you'll have to provide an array of paths to all of your template files using the purge option in tailwind.config.js
`purge: [
        './src/**/*.html',
        './src/**/*.vue',
        './src/**/*.jsx',
      ],  `

Reference: https://tailwindcss.com/docs/optimizing-for-production#basic-usage

**Comment by nagad814** [comment]
so got a clean clone of the repo. and run `yarn build`.
got below error

$ npm-run-all -s clean -p postcss:build parcel:build
$ rm -rf dist .cache
$ postcss src/assets/css/index.pcss -o src/assets/css/index.css --env production
$ parcel build src/index.html
Please install PostCSS 8 or above
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "postcss:build" exited with 1.
error Command failed with exit code 1.

**Comment by nagad814** [comment]
fixed the error with downgrading to postcss-cli@7.x

**Comment by mod7ex** [comment]
i still see the same error even that i have provided template paths 
`warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set 'purge: false' in your Tailwind config file to silence this warning.
`

**Comment by JuanVqz** [comment]
@Modex987 did you fix it?
